<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>pinky_description</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="byeongkyu@todo.todo">byeongkyu</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>xacro</depend>

  <!-- robot_state_publisher : 
    /robot_description, 
    /joint_states 토픽에서 로봇 모델과 로봇 관절 정보를 불러와 TF 정보를 발행한다. 
    출력 : '/base_link 등의 정보'
    -->
  <depend>robot_state_publisher</depend>

  <!-- joint_state_publisher :
  입력:
    /robot_description 파라미터
  출력:
    /joint_states
    -->
  <depend>joint_state_publisher</depend>
  <depend>joint_state_publisher_gui</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
